//! Line-delimited JSON-RPC framing for the engine's stdio transport.
//!
//! Shapes here mirror the bindings generated by `codex app-server generate-ts`.
//! Keep this module free of Scientify concepts so the engine stays replaceable.

use serde::Serialize;
use serde_json::{json, Value};

/// Client identity sent during `initialize` (see `ClientInfo` in the bindings).
#[derive(Serialize)]
pub struct ClientInfo<'a> {
    pub name: &'a str,
    pub title: Option<&'a str>,
    pub version: &'a str,
}

/// A request line: one JSON object per line, newline terminated.
pub fn request(id: u64, method: &str, params: Value) -> String {
    let mut line =
        json!({ "jsonrpc": "2.0", "id": id, "method": method, "params": params }).to_string();
    line.push('\n');
    line
}

/// `initialize` is the first exchange. Experimental methods stay off: the shell
/// only needs the stable surface, and opting in would widen the contract.
pub fn initialize(id: u64, name: &str, title: &str, version: &str) -> String {
    request(
        id,
        "initialize",
        json!({
            "clientInfo": ClientInfo { name, title: Some(title), version },
            "capabilities": { "experimentalApi": false, "requestAttestation": false }
        }),
    )
}

/// Read the id of a JSON-RPC response, ignoring notifications.
pub fn response_id(value: &Value) -> Option<u64> {
    value.get("id").and_then(Value::as_u64)
}

/// A message arriving from the engine.
///
/// The three kinds must be told apart: answering a server request is mandatory
/// (an unanswered approval blocks the turn), while a notification is one-way.
#[derive(Debug, PartialEq)]
pub enum Incoming {
    /// The reply to a request this host issued.
    Response { id: u64, value: Value },
    /// A request the engine makes of this host, such as an approval prompt.
    ServerRequest {
        id: Value,
        method: String,
        params: Value,
    },
    /// A one-way event.
    Notification { method: String, params: Value },
}

pub fn classify(line: &str) -> Option<Incoming> {
    let value: Value = serde_json::from_str(line.trim()).ok()?;
    let method = value.get("method").and_then(Value::as_str);
    match (value.get("id"), method) {
        (Some(id), Some(method)) => Some(Incoming::ServerRequest {
            id: id.clone(),
            method: method.to_string(),
            params: value.get("params").cloned().unwrap_or(Value::Null),
        }),
        (Some(id), None) => id.as_u64().map(|id| Incoming::Response { id, value }),
        (None, Some(method)) => Some(Incoming::Notification {
            method: method.to_string(),
            params: value.get("params").cloned().unwrap_or(Value::Null),
        }),
        (None, None) => None,
    }
}

/// Flatten an incoming message into the shape handed to the frontend.
///
/// This is the only place engine-specific framing becomes a UI contract, so the
/// mapping is deliberately small and stable.
pub fn describe(incoming: &Incoming) -> Value {
    match incoming {
        Incoming::Response { .. } => Value::Null,
        Incoming::ServerRequest { id, method, params } => json!({
            "kind": "request",
            "id": id,
            "method": method,
            "params": params,
        }),
        Incoming::Notification { method, params } => json!({
            "kind": "notification",
            "method": method,
            "params": params,
        }),
    }
}

/// Answer a server-initiated request.
///
/// `RequestId` is a string or a number, so the id is echoed exactly as received
/// rather than normalised.
pub fn response(id: &Value, result: Value) -> String {
    let mut line = json!({ "jsonrpc": "2.0", "id": id, "result": result }).to_string();
    line.push('\n');
    line
}

/// Extract `result`, or surface a JSON-RPC error as text.
pub fn result(value: Value) -> Result<Value, String> {
    if let Some(error) = value.get("error") {
        let message = error
            .get("message")
            .and_then(Value::as_str)
            .unwrap_or("引擎返回了未说明的错误。");
        return Err(message.to_string());
    }
    value
        .get("result")
        .cloned()
        .ok_or_else(|| "引擎响应缺少 result。".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn initialize_enables_neither_experimental_api_nor_attestation() {
        let line = initialize(1, "scientify", "Scientify", "0.3.0");
        assert!(line.ends_with('\n'));
        let value: Value = serde_json::from_str(&line).unwrap();
        assert_eq!(value["method"], "initialize");
        assert_eq!(value["params"]["capabilities"]["experimentalApi"], false);
        assert_eq!(value["params"]["clientInfo"]["name"], "scientify");
    }

    #[test]
    fn notifications_without_an_id_do_not_satisfy_a_response() {
        let notification: Value = serde_json::from_str(r#"{"method":"thread/started"}"#).unwrap();
        assert_eq!(response_id(&notification), None);
    }

    #[test]
    fn jsonrpc_errors_become_readable_text() {
        let value: Value = serde_json::from_str(r#"{"id":1,"error":{"message":"boom"}}"#).unwrap();
        assert_eq!(result(value).unwrap_err(), "boom");
    }

    #[test]
    fn responses_requests_and_notifications_are_told_apart() {
        // A response to our own request.
        assert!(matches!(
            classify(r#"{"id":1,"result":{}}"#),
            Some(Incoming::Response { id: 1, .. })
        ));
        // A server request carries both an id and a method.
        let request = classify(
            r#"{"id":"a1","method":"item/commandExecution/requestApproval","params":{"turnId":"t"}}"#,
        );
        assert!(matches!(request, Some(Incoming::ServerRequest { .. })));
        match request.unwrap() {
            Incoming::ServerRequest { id, params, .. } => {
                // String ids must survive verbatim; the engine rejects invented ones.
                assert_eq!(id, Value::String("a1".into()));
                assert_eq!(params["turnId"], "t");
            }
            _ => unreachable!(),
        }
        // A notification has a method but no id.
        assert!(matches!(
            classify(r#"{"method":"turn/started","params":{}}"#),
            Some(Incoming::Notification { .. })
        ));
        assert_eq!(classify("not json"), None);
        assert_eq!(classify(r#"{"jsonrpc":"2.0"}"#), None);
    }

    #[test]
    fn a_server_request_is_described_with_its_id_so_it_can_be_answered() {
        let incoming = classify(
            r#"{"id":7,"method":"item/fileChange/requestApproval","params":{"reason":"write"}}"#,
        )
        .unwrap();
        let described = describe(&incoming);
        assert_eq!(described["kind"], "request");
        assert_eq!(described["id"], 7);
        assert_eq!(described["method"], "item/fileChange/requestApproval");
        let answer = response(&described["id"], json!({ "decision": "accept" }));
        assert!(answer.contains(r#""decision":"accept""#));
    }
}
